a = int(input("Enter a number: "))
b = int(input("Enter a number: "))

print("Addition of a and b is :",a+b)   
print("Subtraction of a and b is :",a-b)
print("Multiplication of a and b is :",a*b)
print("Division of a and b is :",a/b)
print("Modulus of a and b is :",a%b)
print("Exponentiation of a and b is :",a**b)
print("Floor Division of a and b is :",a//b)
print("Square Root of a and b is :",a**0.5)
print("Square Root of b and a is :",b**0.5)
print("Square Root of a and b is :",a**0.5)
print("Square Root of b and a is :",b**0.5)
print("Square Root of a and b is :",a**0.5)
print("Square Root of b and a is :",b**0.5)